server:
  port: 8084
  #port: ${PORT:${SERVER_PORT:0}} #para poner puertos randoms

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/Microservicios
    username: JC
    password: JC123root
    drive: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  application:
    name: USUARIO-SERVICE #Nombre del microservicio
  config:
    import: optional:configserver:http://localhost:8090
  profiles:
    active: prod
####### Comentamos esto que no usaremos mientras usemos el config client
#eureka:
#  instance: #indicamos la instancia
#    prefer-ip-address: true
    #Y en lugar de la ip por defecto colocariamos instance-id:${spring.application.name}:${spring.application.instace_id:${random.value}}
    #instance-id:
     # ${spring.application.name}:${spring.application.instace_id:${random.value}}
#  client:
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka


######### RESILENCE4J #############
resilience4j:
  circuitbreaker:
    instances:
      # Configuracion para el Circuit Breaker
      myCircuitBreakerForNotUserFound:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

  bulkhead:
    instances:
      # Configuracion para el Bulkhead
      myBulkhead:
        maxConcurrentCalls: 10
        maxWaitDuration: 100

  timelimiter:
    instances:
      # Configuracion para el Time Limiter
      myTimeLimiter:
        timeoutDuration: 500
  retry:
    instances:
      myRetry:
        max-attempts: 3
        waitDuration: 500ms
        retryExceptions:
          - java.io.IOException
management:
  health:
    circuitbreakers:
      enable: true
    endpoints:
      web:
        exposure:
          include: health
    endpoint:
      health:
        show-details: always