
server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Microservices
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: HOTEL-SERVICE
  config:
    ## Si dejamos optional toma el archivo por defecto ademas si quitamos el application name del github( archivo de configuracion )
    ## tomara el nombre de este archivo es decir HOTEL-SERVICE
    import: optional:configserver:http://localhost:8090
  profiles:
    active: prod
#eureka:
#  instance: #indicamos la instancia
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka